version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local123
      POSTGRES_DB: task-1-encryption
    volumes:
      - task-1-encryption:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  task-1-encryption:
